sudo: required
services:
  - docker
before_install:
  - docker build -t xarentek/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true xarentek/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-west-2-942470232070"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$aws_access_key"
  secret_access_key:
    secure: "$aws_secret_key"
